### ISSUE TITLE
When PR was assigned to group it doesn't show up under "Assigned To Me" section

### ISSUE THREAD

**Issue by kaufmd** [rstedman/tfs-pullrequest-dashboard#53] opened 2019-10-07 12:29 UTC
Current state:
When an open PR is assigned to a group that I am member of, the PR is not showing up under the "Assigned To Me" section.

Target state:
Please show open PRs under the "Assigned To Me" section or introduce a new section with a name such as "Assigned to one of your groups" to show these kind of PRs.

**Comment by rstedman** [comment] 2019-12-08 19:36
duplicate of #46

**Closed by rstedman** 2019-12-08 19:36 UTC
Labels: duplicate
