### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by joodies** [rstedman/tfs-pullrequest-dashboard#2] opened 2017-06-22 09:37 UTC
Microsoft Visual Studio Team Foundation Server
Version 15.112.26307.0

Got following error msg:

tfs-pullrequest-dashboard by ryanstedman failed to load.Learn More about this extension, including available support options.

**Comment by rstedman** [comment] 2017-06-24 13:19
If you open the developer tools in the browser you're using after you see that error, are there any errors logged in the console?  If so, could you paste any errors here?

**Comment by rstedman** [comment] 2017-12-16 19:50
closing.  no further detail provided by originator, and unable to reproduce.

**Closed by rstedman** 2017-12-16 19:50 UTC
Labels: bug
